- name: Seed ragnarok logs Database
  sudo: yes
  mysql_db:
    name: ragnarok_logs
    state: import
    target: /srv/ragnarok/sql-files/logs.sql
    login_user: "{{mysql_root_user}}"
    login_password: "{{mysql_root_pass}}"

- name: Seed ragnarok main Database
  sudo: yes
  mysql_db:
    name: ragnarok
    state: import
    target: /srv/ragnarok/sql-files/{{item}}.sql
    login_user: "{{mysql_root_user}}"
    login_password: "{{mysql_root_pass}}"
  with_items:
    - main
    - item_db
    - mob_db
    - mob_skill_db
    - item_db_re
    - mob_db_re
    - mob_skill_db_re
    - item_db2
    - mob_db2
    - mob_skill_db2
