#
# Install
#
- name: Update Cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install Ragnarok Server Dependancies
  action: apt name={{item}} state=present
  sudo: yes
  with_items:
    - gcc
    - make
    - git
    - mysql-server
    - libmysqlclient-dev
    - zlib1g-dev
    - libpcre3-dev
    - screen
    - python-mysqldb

#
# Grab/Update Server
#
- name: is this the first install?
  command: test -d /srv/ragnarok
  register: first_install_check
  ignore_errors: yes
  changed_when: False

- name: Clone Ragnarok Server
  git: repo=https://github.com/HerculesWS/Hercules.git dest=/srv/ragnarok/
  sudo: yes
  when: first_install_check.rc != 0

- name: Check if update is available
  shell: 'cd /srv/ragnarok && git fetch && test "$(git rev-parse HEAD)" = "$(git rev-parse @{u})"'
  ignore_errors: yes
  register: update_check
  sudo: yes
  changed_when: False

- name: Update Ragnarok Server
  git: force=yes repo=https://github.com/HerculesWS/Hercules.git dest=/srv/ragnarok/ update=yes
  sudo: yes
  when: update_check.rc != 0

#
# MySQL
#
- name: Make sure mysql is on
  service: name=mysql state=running
  sudo: yes

- name: Add a mysql database for ragnarok
  mysql_db:
    db: ragnarok
    state: present
    login_user: "{{mysql_root_user}}"
    login_password: "{{mysql_root_pass}}"

- name: Add a mysql database for ragnarok logs
  mysql_db:
    db: ragnarok_logs
    state: present
    login_user: "{{mysql_root_user}}"
    login_password: "{{mysql_root_pass}}"

- name: Add a mysql user for ragnarok
  mysql_user:
    user: "{{mysql_user}}"
    password: "{{mysql_pass}}"
    host: localhost
    state: present
    login_user: "{{mysql_root_user}}"
    login_password: "{{mysql_root_pass}}"
    priv: ragnarok_logs.*:ALL/ragnarok.*:ALL

#
# update & first install
#

- name: Plugin check
  file: path=/srv/ragnarok/plugins/empty.txt state=absent
  sudo: yes

- name: check for plugins
  shell: test -n "$(find /srv/ragnarok/plugins -type f)"
  changed_when: False
  ignore_errors: yes
  register: plugins_exist

- name: install ragnarok (no plugins)
  shell: cd /srv/ragnarok && ./configure && make clean && make sql
  sudo: yes
  when: (first_install_check.rc != 0 or update_check.rc != 0) and plugins_exist.rc != 0

- name: install ragnarok (with plugins)
  shell: cd /srv/ragnarok && ./configure && make clean && make sql plugins
  sudo: yes
  when: (first_install_check.rc != 0 or update_check.rc != 0) and plugins_exist.rc == 0

#
# first install only
#

- include: first_install.yml
  when: first_install_check.rc != 0

#
# Permissions/Credentials
#

- include: configuration.yml

- name: add system ragnarok user
  user: name=ragnarok shell=/usr/sbin/nologin state=present
  sudo: yes

- name: set permissions on Ragnarok Server folder
  file: recurse=yes owner=ragnarok group=ragnarok path=/srv/ragnarok
  sudo: yes
