- name: Install MySQL and Dependancies
  apt: name={{item}} state=present
  sudo: yes
  register:  first_install
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start MySQL and Start on Boot
  service: name=mysql enabled=yes state=started
  sudo: yes

- include: first_install.yml
  when: first_install.changed
