- include: ../../install_daemon.yml
  vars:
    daemon_name: MySQL
    daemon_service: mysql
    daemon_package: mysql-server

- name: Adds Python MySQL support on Debian/Ubuntu
  apt: pkg="python-mysqldb" state=present
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Adds Python MySQL support on RedHat/CentOS
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat'
  sudo: yes

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user: user="" host="{{ ansible_fqdn }}" state="absent"

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"

- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user: user="root" password="root" host="::1"

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user: user="root" password="root" host="127.0.0.1"

- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user: user="root" password="root" host="localhost"

- name: Secures the MySQL root user for server_hostname domain
  mysql_user: user="root" password="root" host="{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: db=test state=absent

- name: Sets the root password
  mysql_user: user=root password="root" host=localhost


