- name: Update Cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Adds Python MySQL support on Debian/Ubuntu
  apt: pkg="python-mysqldb" state=present
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Adds Python MySQL support on RedHat/CentOS
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat'
  sudo: yes

- name: Install rAthena Dependancies
  action: apt name={{item}} state=present
  sudo: yes
  with_items:
    - gcc
    - make
    - git
    - mysql-server
    - libmysqlclient-dev
    - zlib1g-dev
    - libpcre3-dev


- name: Make sure mysql is on
  service: name=mysql state=running
  sudo: yes

- name: Add a mysql database for rathena
  mysql_db: db=rathena state=present

- name: Add a mysql user for rathena
  mysql_user: user=rathena password=ragnarok host=localhost priv=rathena.*:ALL state=present

- name: is rAthena already installed?
  command: test -d /srv/ragnarok
  register: install_check
  ignore_errors: yes
  changed_when: False

- name: add rathena user
  user: name=rathena
  sudo: yes

- name: Clone/update rAthena
  git: force=yes repo=https://github.com/rathena/rathena.git dest=/srv/ragnarok/ update=yes
  sudo: yes

- name: set permissions on rAthena folder
  file: recurse=yes owner=rathena group=rathena path=/srv/ragnarok
  sudo: yes

- name: install rAthena
  shell: cd /srv/ragnarok && ./configure && make clean && make server
  sudo: yes
  when: install_check.rc != 0

- name: Seed rAthena Database
  shell: cat /srv/ragnarok/sql-files/main.sql | mysql -urathena -p rathena
  sudo: yes
  when: install_check.rc != 0

- name: Setup login server
  shell: echo "UPDATE rathena.login SET userid = 'ragnarok', user_pass = 'ragnarok' where account_id = 1;" | mysql -urathena -p rathena
  when: install_check.rc != 0

